-- AULA ORDENAÇÃO  TOP | ORDER BY

SELECT 
  TOP 10 -- SELECIONA OS 10 MAIORES OU MENORES DEPENDENDO DO ORDER BY (DESC, ASC)
  t.*
FROM
  tb_tablename AS t
ORDER BY t.column1 DESC, t.column2 ASC -- DESC (MAIORES) | ASC (MENORES)
