-- DTL (DATA TRANSACTION LANGUAGE) - BEGIN TRANSACTION | COMMIT | ROLLBACK

BEGIN TRANSACTION
UPDATE nome_tabela
  SET coluna = 'novo valor'
  WHERE coluna = 'condição'

-- ROLLBACK TUDO ACIMA É CANCELADO
COMMIT -- ENCERRA A TRANSACTION
